language: node_js
node_js:
    - v10.16.0
before_install:
    - npm install -g typescript@3.5.3
script:
    - npm run lint
    - tsc
    - npm run preact_build
# deploy:
#     provider: firebase
#     token:
#         secure:
